module LLT
  module Constants
    CARDINALS = {
      "duo"           => [[2, 1, :m], [2, 4, :m], [2, 1, :n], [2, 4, :n]],
      "duorum"        => [[2, 2, :m], [2, 2, :n]],
      "duobus"        => [[2, 3, :m], [2, 6, :m], [2, 3, :n], [2, 6, :n]],
      "duos"          => [[2, 4, :m]],
      "duae"          => [[2, 1, :f]],
      "duarum"        => [[2, 2, :f]],
      "duabus"        => [[2, 3, :f], [2, 6, :f]],
      "duas"          => [[2, 4, :f]],
      "ambo"          => [[2, 1, :m], [2, 4, :m], [2, 1, :n], [2, 4, :n]],
      "amborum"       => [[2, 2, :m], [2, 2, :n]],
      "ambobus"       => [[2, 3, :m], [2, 6, :m], [2, 3, :n], [2, 6, :n]],
      "ambos"         => [[2, 4, :m]],
      "ambae"         => [[2, 1, :f]],
      "ambarum"       => [[2, 2, :f]],
      "ambabus"       => [[2, 3, :f], [2, 6, :f]],
      "ambas"         => [[2, 4, :f]],
      "tres"          => [[3, 1, :m], [3, 1, :f], [3, 4, :m], [3, 4, :f]],
      "trium"         => [[3, 2, :m], [3, 2, :f], [3, 2, :n]],
      "tribus"        => [[3, 3, :m], [3, 3, :f], [3, 3, :n], [3, 6, :m], [3, 6, :f], [3, 6, :n]],
      "tria"          => [[3, 1, :n], [3, 4, :n]],
      "milia"         => [[1000, 1, nil], [1000, 4, nil]],
      "milium"        => [[1000, 2, nil]],
      "milibus"       => [[1000, 3, nil], [1000, 6, nil]],
      "quattuor"      => [[4, nil, nil]],
      "quinque"       => [[5, nil, nil]],
      "sex"           => [[6, nil, nil]],
      "septem"        => [[7, nil, nil]],
      "octo"          => [[8, nil, nil]],
      "novem"         => [[9, nil, nil]],
      "decem"         => [[10, nil, nil]],
      "undecim"       => [[11, nil, nil]],
      "duodecim"      => [[12, nil, nil]],
      "tredecim"      => [[13, nil, nil]],
      "quattuordecim" => [[14, nil, nil]],
      "quindecim"     => [[15, nil, nil]],
      "sedecim"       => [[16, nil, nil]],
      "septendecim"   => [[17, nil, nil]],
      "mille"         => [[1000, nil, nil]],
      "duodeviginti"  => [[18, nil, nil]]
    }
  end
end
