module LLT
  module Constants
    PREPOSITIONS = { "in"       =>[true, true, false],
                     "sub"      =>[true, true, false],
                     "super"    =>[true, true, false],
                     "ad"       =>[true, false, false],
                     "a"        =>[false, true, false],
                     "ab"       =>[false, true, false],
                     "abs"      =>[false, true, false],
                     "e"        =>[false, true, false],
                     "ex"       =>[false, true, false],
                     "de"       =>[false, true, false],
                     "cum"      =>[false, true, true],
                     "coram"    =>[false, true, true],
                     "palam"    =>[false, true, false],
                     "sine"     =>[false, true, false],
                     "pro"      =>[false, true, false],
                     "prae"     =>[false, true, false],
                     "adversus" =>[true, false, true],
                     "adversum" =>[true, false, true],
                     "apud"     =>[true, false, false],
                     "circa"    =>[true, false, false],
                     "circum"   =>[true, false, true],
                     "citra"    =>[true, false, false],
                     "erga"     =>[true, false, false],
                     "extra"    =>[true, false, false],
                     "infra"    =>[true, false, false],
                     "inter"    =>[true, false, false],
                     "intra"    =>[true, false, false],
                     "iuxta"    =>[true, false, false],
                     "ob"       =>[true, false, false],
                     "penes"    =>[true, false, true],
                     "per"      =>[true, false, false],
                     "post"     =>[true, false, false],
                     "praeter"  =>[true, false, false],
                     "prope"    =>[true, false, false],
                     "propter"  =>[true, false, false],
                     "secundum" =>[true, false, true],
                     "supra"    =>[true, false, false],
                     "trans"    =>[true, false, false],
                     "ultra"    =>[true, false, false],
                     "ante"     =>[true, false, true],
                     "contra"   =>[true, false, true],
                     "circiter" =>[true, false, true],
                     "cis"      =>[true, false, false]
    }
  end
end
